// src/campaign/CampaignData.js
// Campaign data (MW-like pacing, original cast & setting).

export const CAMPAIGN_KEY = 'strikegy_campaign_v1';

// CAST (original; avoid direct CoD names)
// - CAPTAIN HART: field commander (mentor)
// - SHADE: stealth operator / recon
// - RAVEN: player callsign
export const CAST = {
  HART: 'CAPTAIN HART',
  SHADE: 'SHADE',
  RAVEN: 'RAVEN',
};

// Framework supports step types:
// - cutscene: camera rails + cinematic bars/fade + input lock
// - say: TTS(EN) + KO subtitles
// - objective: sets current objective + adds to checklist
// - reach: reach trigger sphere in campaign map
// - kill: reach kill count
// - complete: mission success
// Runtime fail handling:
// - mission.failOnDeath: true => death triggers fail overlay

export const CampaignDB = {
  missions: {
    c1_m1_insertion: {
      id: 'c1_m1_insertion',
      title: 'CH1 M1 — Insertion',
      chapter: 1,
      map: 'maps/campaign/ch1_m1_insertion.json',
      bots: { blue: 0, red: 8 },
      nextMissionId: 'c1_m2_blacksite',
      // Campaign rules (override PvP systems)
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      // Fixed loadout (no purchases). Slots stay the same.
      loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['frag','flash','smoke'], extras: ['impact'] },
      failOnDeath: true,
      // Optional: mission time limit (seconds). 0 = none.
      timeLimitSec: 0,

      // Script sequence (10~20min target; MVP is short but structured for expansion)
      script: [
        { id:'cs_intro', type:'cutscene', duration:7.2, lockPlayer:true,
          cinematic:{ bars:true, fadeIn:0.5, fadeOut:0.4 },
          camera:[
            { t:0.0, pos:[-155,3.4,-20], look:[-124,2.1,-2] },
            { t:2.4, pos:[-146,3.8,-10], look:[-120,2.2, 8] },
            { t:4.8, pos:[-136,4.1,  6], look:[-106,2.3,18] },
            { t:7.2, pos:[-126,3.6, 18], look:[ -94,2.2,28] },
          ],
        },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Raven—sun’s up. We’re late, so we stay quiet.",
          ko:'레이븐—해가 떴다. 늦었으니 조용히 간다.',
        },
        { id:'obj_rally', type:'objective', key:'rally', text:'집결 지점으로 이동' },
        { id:'reach_rally', type:'reach', trigger:'rally', label:'집결 지점' },
        { id:'dlg_2', type:'say', speaker:CAST.SHADE,
          en:"Camp comms are on a short loop. Tap the relay—then we move.",
          ko:'캠프 통신이 짧게 반복돼. 중계기 건드리고 바로 빠져.',
        },
        { id:'obj_relay', type:'objective', key:'relay', text:'임시 중계기 해킹' },
        { id:'hack', type:'interact', trigger:'rally', label:'중계기', hint:'E로 해킹',
          toast:'신호 루프 차단', objectiveKey:'relay', checkpointId:'relay' },
        { id:'dlg_3', type:'say', speaker:CAST.HART,
          en:"They heard that. Take the outer ring, clean what follows.",
          ko:'들켰다. 외곽으로 빠지며 뒤따르는 놈들 정리해.',
        },
        { id:'obj_elim', type:'objective', key:'elim6', text:'추격 적 제거 (6)' },
        { id:'kill_6', type:'kill', count:6, team:'red' },
        { id:'dlg_4', type:'say', speaker:CAST.SHADE,
          en:"Dust is shifting—watch the ridge. Exfil marker is live.",
          ko:'먼지 흐름이 바뀐다—능선 조심. 탈출 마커 열림.',
        },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'탈출 지점 확보' },
        { id:'wait_pickup', type:'wait', sec:3.5, text:'픽업 신호 송신 중', checkpointId:'pickup_ping' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
          { id:'end', type:'complete' }
        ],
      },
  
      c1_m1_insertion_alt: {
        id: 'c1_m1_insertion_alt',
        title: 'CH1 M1 — Insertion (Alt)',
        chapter: 1,
        map: 'maps/campaign/ch1_m1_insertion.json',
        bots: { blue: 0, red: 8 },
        nextMissionId: 'c1_m2_blacksite',
        rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
        loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['frag','flash','smoke'], extras: ['impact'] },
        failOnDeath: true,
        timeLimitSec: 0,
        script: [
          {
            id: 'dlg_1',
          type: 'say',
          speaker: CAST.HART,
          en: "Raven. Eyes up. We’ve got movement in the dust.",
          ko: '레이븐. 전방 주시. 먼지 속에 움직임이 있다.',
        },
        {
          id: 'obj_rally',
          type: 'objective',
          key: 'rally',
          text: '집결 지점으로 이동',
        },
        {
          id: 'reach_rally',
          type: 'reach',
          trigger: 'rally',
          label: '집결 지점',
        },
        {
          id: 'dlg_2',
          type: 'say',
          speaker: CAST.SHADE,
          en: "Two patrols. East side. Keep your silhouette low.",
          ko: '순찰 둘. 동쪽. 실루엣 낮춰.',
        },
        {
          id: 'obj_elim',
          type: 'objective',
          key: 'elim5',
          text: '적 5명 제거',
        },
        {
          id: 'kill_5',
          type: 'kill',
          count: 5,
          team: 'red',
        },
        {
          id: 'dlg_3',
          type: 'say',
          speaker: CAST.HART,
          en: "Clean. Don’t linger—exfil is north. Move.",
          ko: '깔끔하다. 지체하지 마—탈출 지점은 북쪽. 이동.',
        },
        {
          id: 'obj_exfil',
          type: 'objective',
          key: 'exfil',
          text: '탈출 지점 확보',
        },
        {
          id: 'reach_exfil',
          type: 'reach',
          trigger: 'exfil',
          label: '탈출 지점',
        },
        {
          id: 'end',
          type: 'complete',
        },
      ],
    },

    // --- CH1: "DUSTLINE" (10 missions, MW-like pacing; original setting/cast) ---
    c1_m2_blacksite: {
      id: 'c1_m2_blacksite',
      title: 'CH1 M2 — Blacksite',
      chapter: 1,
      map: 'maps/campaign/ch1_m2_blacksite.json',
      bots: { blue: 2, red: 10 },
      nextMissionId: 'c1_m3_convoy',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg1', secondary: 'pistol1', grenades: ['flash','frag','smoke'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'cs_entry', type:'cutscene', duration:6.6, lockPlayer:true,
          cinematic:{ bars:true, fadeIn:0.4, fadeOut:0.25 },
          camera:[
            { t:0.0, pos:[-85,3.6,-70], look:[-60,2.4,-42] },
            { t:2.0, pos:[-70,3.3,-55], look:[-40,2.2,-25] },
            { t:4.0, pos:[-52,3.0,-40], look:[-20,2.0, -6] },
            { t:6.6, pos:[-42,2.8,-28], look:[-10,2.0, 10] },
          ],
        },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Blacksite door. No shop, no kit—just what you carry.",
          ko:'블랙사이트 문이다. 상점/키트 없음—들고 있는 걸로 간다.',
        },
        { id:'obj_breach', type:'objective', key:'breach', text:'출입문 돌파' },
        { id:'breach', type:'interact', trigger:'breach', label:'출입문', hint:'E로 돌파',
          toast:'문 개방', objectiveKey:'breach', checkpointId:'breach' },
        { id:'dlg_2', type:'say', speaker:CAST.SHADE,
          en:"Camera grid is old. Move fast between the lights.",
          ko:'감시망이 구식이야. 조명 사이로 빠르게.',
        },
        { id:'obj_intel', type:'objective', key:'intel', text:'자료실에서 데이터 확보' },
        { id:'reach_intel', type:'reach', trigger:'intel', label:'자료실' },
        { id:'grab', type:'interact', trigger:'intel', label:'단말기', hint:'E로 다운로드 시작',
          toast:'다운로드 시작', checkpointId:'dl_start' },
        { id:'wait_dl', type:'wait', sec:8.0, text:'데이터 다운로드', objectiveKey:'intel', checkpointId:'dl_done' },
        { id:'dlg_3', type:'say', speaker:CAST.HART,
          en:"Alarm—hold that corridor! Thirty seconds!",
          ko:'경보! 복도에서 버텨! 30초!',
        },
        { id:'obj_hold', type:'objective', key:'hold', text:'복도 방어' },
        { id:'defend', type:'defend', sec:30, text:'위치 사수', objectiveKey:'hold', checkpointId:'hold_30' },
        { id:'dlg_4', type:'say', speaker:CAST.SHADE,
          en:"Route’s clear. Exfil on the far side.",
          ko:'루트 확보. 반대편으로 탈출.',
        },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'탈출 지점으로 이동' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m3_convoy: {
      id: 'c1_m3_convoy',
      title: 'CH1 M3 — Convoy',
      chapter: 1,
      map: 'maps/campaign/ch1_m3_convoy.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m4_bridge',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar2', secondary: 'pistol1', grenades: ['frag','smoke','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Convoy’s rolling. We don’t stop it—we cut its memory.",
          ko:'호송대가 이동 중이다. 멈추는 게 아니라 ‘기억’을 자른다.',
        },
        { id:'obj_amb', type:'objective', key:'ambush', text:'매복 지점 확보' },
        { id:'reach_amb', type:'reach', trigger:'ambush', label:'매복 지점' },
        { id:'wait_pass', type:'wait', sec:5.0, text:'호송대 접근 대기', checkpointId:'convoy_in' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Target case—rear truck. Take it and burn the route.",
          ko:'목표 케이스—후미 트럭. 회수하고 루트를 태워.',
        },
        { id:'obj_disable', type:'objective', key:'case', text:'케이스 회수' },
        { id:'pickup', type:'interact', trigger:'pickup', label:'케이스', hint:'E로 회수',
          toast:'케이스 확보', objectiveKey:'case', checkpointId:'case' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"They’re turning back—deny the road. Ten hostiles.",
          ko:'되돌아온다—도로 차단. 적 10.',
        },
        { id:'obj_elim', type:'objective', key:'elim10', text:'적 10명 제거' },
        { id:'kill_10', type:'kill', count:10, team:'red' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m4_bridge: {
      id: 'c1_m4_bridge',
      title: 'CH1 M4 — Bridge',
      chapter: 1,
      map: 'maps/campaign/ch1_m4_bridge.json',
      bots: { blue: 3, red: 14 },
      nextMissionId: 'c1_m5_city',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'lmg1', secondary: 'pistol1', grenades: ['smoke','frag','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Bridge is the throat. We cross, or we choke.",
          ko:'다리는 목줄이다. 건너야 숨을 쉰다.',
        },
        { id:'obj_bridge', type:'objective', key:'bridge', text:'교량 진입' },
        { id:'reach_bridge', type:'reach', trigger:'bridge', label:'교량' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Smoke then sprint. Don’t bunch up.",
          ko:'연막 치고 전력 질주. 뭉치지 마.',
        },
        { id:'obj_push', type:'objective', key:'push', text:'교량 돌파' },
        { id:'defend_mid', type:'defend', sec:22, text:'중간 지점 돌파', objectiveKey:'push', checkpointId:'bridge_mid' },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'교량 끝 확보' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m5_city: {
      id: 'c1_m5_city',
      title: 'CH1 M5 — Cityline',
      chapter: 1,
      map: 'maps/campaign/ch1_m5_city.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m6_trench',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['flash','smoke','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"City’s awake. Civilians gone—only echoes left.",
          ko:'도시가 깨어났다. 민간인은 사라지고, 메아리만 남았다.',
        },
        { id:'obj_street', type:'objective', key:'street', text:'골목길로 진입' },
        { id:'reach_street', type:'reach', trigger:'street', label:'골목' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"We need eyes. Rooftop gives angles—take it.",
          ko:'시야가 필요해. 옥상에서 각을 잡아—올라가.',
        },
        { id:'obj_roof', type:'objective', key:'roof', text:'고지 확보' },
        { id:'reach_roof', type:'reach', trigger:'rooftop', label:'고지' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"Mark the route. Then we disappear.",
          ko:'루트 표시하고 사라진다.',
        },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'도시 외곽으로 탈출' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m6_trench: {
      id: 'c1_m6_trench',
      title: 'CH1 M6 — Trenchwork',
      chapter: 1,
      map: 'maps/campaign/ch1_m6_trench.json',
      bots: { blue: 3, red: 16 },
      nextMissionId: 'c1_m7_ridge',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'sg1', secondary: 'pistol1', grenades: ['smoke','frag','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"No-man’s-land. Keep your head down—sound carries.",
          ko:'노맨즈랜드. 머리 숙여—소리가 멀리 간다.',
        },
        { id:'obj_l1', type:'objective', key:'line1', text:'1차 참호선 확보' },
        { id:'reach_l1', type:'reach', trigger:'line1', label:'1차 참호선' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"They’re dug in. Push by segments—don’t overextend.",
          ko:'파고들어있다. 구간별로 밀어—깊게 나가지 마.',
        },
        { id:'obj_l2', type:'objective', key:'line2', text:'2차 참호선 확보' },
        { id:'reach_l2', type:'reach', trigger:'line2', label:'2차 참호선' },
        { id:'obj_l3', type:'objective', key:'line3', text:'3차 참호선 확보' },
        { id:'reach_l3', type:'reach', trigger:'line3', label:'3차 참호선' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m7_ridge: {
      id: 'c1_m7_ridge',
      title: 'CH1 M7 — Ridgeline',
      chapter: 1,
      map: 'maps/campaign/ch1_m7_ridge.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m8_counter',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'sr1', secondary: 'pistol1', grenades: ['smoke','flash','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Relay tower. If it stays up, they see everything.",
          ko:'중계탑이다. 살아있으면 놈들이 전부 본다.',
        },
        { id:'obj_yard', type:'objective', key:'yard', text:'야적장 진입' },
        { id:'reach_yard', type:'reach', trigger:'yard', label:'야적장' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Plant a charge—make it look like an accident.",
          ko:'폭약 설치해. 사고처럼 보이게.',
        },
        { id:'obj_tower', type:'objective', key:'tower', text:'중계장치 파괴' },
        { id:'inter_tower', type:'interact', trigger:'tower', label:'중계장치', hint:'E로 폭약 설치',
          toast:'폭약 설치', objectiveKey:'tower', checkpointId:'tower_charge' },
        { id:'wait_boom', type:'wait', sec:3.0, text:'기폭', checkpointId:'boom' },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'이탈' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m8_counter: {
      id: 'c1_m8_counter',
      title: 'CH1 M8 — Counterstrike',
      chapter: 1,
      map: 'maps/campaign/ch1_m8_counter.json',
      bots: { blue: 3, red: 18 },
      nextMissionId: 'c1_m9_lab',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'lmg2', secondary: 'pistol1', grenades: ['smoke','frag','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Subway’s a straight line—until it isn’t. Stay sharp.",
          ko:'지하철은 직선이다… 그렇지 않을 때까지. 집중해.',
        },
        { id:'obj_plat', type:'objective', key:'platform', text:'플랫폼 접근' },
        { id:'reach_plat', type:'reach', trigger:'platform', label:'플랫폼' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Switch room. We reroute the gates.",
          ko:'전환실. 게이트 우회한다.',
        },
        { id:'obj_switch', type:'objective', key:'switch', text:'전환기 조작' },
        { id:'inter_switch', type:'interact', trigger:'switch', label:'전환기', hint:'E로 조작',
          toast:'선로 전환', objectiveKey:'switch', checkpointId:'switch' },
        { id:'wait_gate', type:'wait', sec:4.0, text:'게이트 개방', checkpointId:'gate_open' },
        { id:'obj_escape', type:'objective', key:'escape', text:'터널을 빠져나가기' },
        { id:'reach_escape', type:'reach', trigger:'escape', label:'탈출' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m9_lab: {
      id: 'c1_m9_lab',
      title: 'CH1 M9 — The Lab',
      chapter: 1,
      map: 'maps/campaign/ch1_m9_lab.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m10_exodus',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg4', secondary: 'pistol1', grenades: ['flash','smoke','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Embassy’s a symbol. We extract the person, not the pride.",
          ko:'대사관은 상징이다. 우리는 자존심이 아니라 ‘사람’을 빼낸다.',
        },
        { id:'obj_gate', type:'objective', key:'gate', text:'정문 접근' },
        { id:'reach_gate', type:'reach', trigger:'gate', label:'정문' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"VIP is inside. Quiet hands.",
          ko:'VIP는 안쪽이다. 손을 조용히.',
        },
        { id:'obj_vip', type:'objective', key:'vip', text:'VIP 확보' },
        { id:'inter_vip', type:'interact', trigger:'vip', label:'VIP', hint:'E로 확보',
          toast:'VIP 확보', objectiveKey:'vip', checkpointId:'vip' },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'호위하며 탈출' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m10_exodus: {
      id: 'c1_m10_exodus',
      title: 'CH1 M10 — Exodus',
      chapter: 1,
      map: 'maps/campaign/ch1_m10_exodus.json',
      bots: { blue: 3, red: 20 },
      nextMissionId: 'c2_m1_blacktide',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar3', secondary: 'pistol1', grenades: ['smoke','flash','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Canyon LZ. If we miss the window, we’re buried here.",
          ko:'협곡 착륙지점. 타이밍 놓치면 여기서 묻힌다.',
        },
        { id:'obj_push', type:'objective', key:'push', text:'전진' },
        { id:'reach_push', type:'reach', trigger:'push', label:'전진 지점' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Hold the bowl—eyes on the ridges.",
          ko:'분지에서 버텨. 능선 주시.',
        },
        { id:'obj_hold', type:'objective', key:'hold', text:'착륙지점 방어' },
        { id:'def_hold', type:'defend', sec:35, text:'착륙지점 사수', objectiveKey:'hold', checkpointId:'lz_hold' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"Bird’s in. Move, move—LZ now!",
          ko:'헬기 도착. 이동, 이동—지금 LZ!',
        },
        { id:'obj_lz', type:'objective', key:'lz', text:'착륙지점 진입' },
        { id:'reach_lz', type:'reach', trigger:'lz', label:'LZ' },
        { id:'end', type:'complete' }
      ],
    },


    // =====================
    // Chapter 2 — Black Tide (20 missions)
    // Tone: MW-style global chase, escalating stakes, heavier narrative density.

    c2_m1_blacktide: {
      id: 'c2_m1_blacktide',
      title: 'CH2 M1 — Black Tide',
      chapter: 2,
      map: 'maps/campaign/ch2_m1_port.json',
      bots: { blue: 4, red: 18 },
      nextMissionId: 'c2_m2_drydock',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['smoke','flash','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"Shipment logged under a dead company. That's your thread.",
          ko:'폐업한 유령 회사 명의로 반입됐다. 그게 실마리야.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'항만 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'항만 외곽' },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Copy. Keep it surgical.",
          ko:'확인. 최대한 깔끔하게.',
        },
        { id:'obj_1', type:'objective', key:'b', text:'컨테이너 구역 확보' },
        { id:'reach_1', type:'reach', trigger:'b', label:'컨테이너' },
        { id:'obj_2', type:'objective', key:'c', text:'선적 서류 회수' },
        { id:'inter_2', type:'interact', trigger:'c', label:'서류함', hint:'E로 회수', toast:'서류 확보', objectiveKey:'c', checkpointId:'c2m1_docs' },
        { id:'dlg_2', type:'say', speaker:CAST.KESTREL,
          en:"They’re moving the cargo. Exfil route marked.",
          ko:'화물을 옮긴다. 탈출 루트 표시한다.',
        },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m2_drydock: {
      id: 'c2_m2_drydock',
      title: 'CH2 M2 — Drydock',
      chapter: 2,
      map: 'maps/campaign/ch2_m1_port.json',
      bots: { blue: 4, red: 22 },
      nextMissionId: 'c2_m3_sandglass',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg2', secondary: 'pistol1', grenades: ['flash','frag'], extras: ['smoke','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"The dockmaster has the ledger. We grab it before it burns.",
          ko:'부두 책임자가 장부를 쥐고 있어. 불타기 전에 가져온다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'조선소 접근' },
        { id:'reach_0', type:'reach', trigger:'a', label:'조선소' },
        { id:'obj_1', type:'objective', key:'b', text:'도크 장악' },
        { id:'def_1', type:'defend', sec:35, text:'도크 사수', objectiveKey:'b', checkpointId:'c2m2_hold' },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Ledger in sight. Move.",
          ko:'장부 확인. 이동.',
        },
        { id:'obj_2', type:'objective', key:'c', text:'장부 확보' },
        { id:'inter_2', type:'interact', trigger:'c', label:'장부', hint:'E로 확보', toast:'장부 확보', objectiveKey:'c', checkpointId:'c2m2_ledger' },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m3_sandglass: {
      id: 'c2_m3_sandglass',
      title: 'CH2 M3 — Sandglass',
      chapter: 2,
      map: 'maps/campaign/ch2_m2_desert.json',
      bots: { blue: 3, red: 26 },
      nextMissionId: 'c2_m4_wadi',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar3', secondary: 'pistol1', grenades: ['smoke','frag'], extras: ['flash','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.KESTREL,
          en:"Convoy route is live. If we miss it, they vanish into the dunes.",
          ko:'호송로가 열렸다. 놓치면 모래바다로 사라진다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'협곡 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'협곡' },
        { id:'obj_1', type:'objective', key:'b', text:'매복 지점 확보' },
        { id:'def_1', type:'defend', sec:30, text:'매복 유지', objectiveKey:'b', checkpointId:'c2m3_ambush' },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Hit the lead truck. Stop the line.",
          ko:'선두를 끊어. 줄을 멈춘다.',
        },
        { id:'obj_2', type:'objective', key:'c', text:'화물 확인' },
        { id:'inter_2', type:'interact', trigger:'c', label:'화물', hint:'E로 확인', toast:'화물 확인', objectiveKey:'c', checkpointId:'c2m3_cargo' },
        { id:'obj_3', type:'objective', key:'exfil', text:'후퇴' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'후퇴 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m4_wadi: {
      id: 'c2_m4_wadi',
      title: 'CH2 M4 — Wadi',
      chapter: 2,
      map: 'maps/campaign/ch2_m2_desert.json',
      bots: { blue: 3, red: 28 },
      nextMissionId: 'c2_m5_greenline',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'dmr1', secondary: 'pistol1', grenades: ['smoke','flash'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"Their radio node is hidden in a dried riverbed. We cut it.",
          ko:'무전 노드가 마른 하천에 숨어있어. 끊는다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'하천으로 이동' },
        { id:'reach_0', type:'reach', trigger:'a', label:'와디' },
        { id:'obj_1', type:'objective', key:'b', text:'통신 장비 접근' },
        { id:'reach_1', type:'reach', trigger:'b', label:'통신 노드' },
        { id:'obj_2', type:'objective', key:'c', text:'장비 파괴' },
        { id:'inter_2', type:'interact', trigger:'c', label:'장비', hint:'E로 해체', toast:'장비 무력화', objectiveKey:'c', checkpointId:'c2m4_node' },
        { id:'dlg_1', type:'say', speaker:CAST.KESTREL,
          en:"Signal flatlined. Now we run.",
          ko:'신호 꺼졌다. 이제 뛰어.',
        },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m5_greenline: {
      id: 'c2_m5_greenline',
      title: 'CH2 M5 — Greenline',
      chapter: 2,
      map: 'maps/campaign/ch2_m3_forest.json',
      bots: { blue: 4, red: 24 },
      nextMissionId: 'c2_m6_ember',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg4', secondary: 'pistol1', grenades: ['flash','smoke'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.YARA,
          en:"We’re not alone in these woods. Watch the treeline—listen.",
          ko:'이 숲에 우리만 있는 게 아니야. 수풀... 소리 들어.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'숲길 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'임도' },
        { id:'obj_1', type:'objective', key:'b', text:'은신 접근' },
        { id:'reach_1', type:'reach', trigger:'b', label:'삼림지' },
        { id:'obj_2', type:'objective', key:'c', text:'은닉 문서 회수' },
        { id:'inter_2', type:'interact', trigger:'c', label:'드롭', hint:'E로 회수', toast:'문서 확보', objectiveKey:'c', checkpointId:'c2m5_drop' },
        { id:'obj_3', type:'objective', key:'exfil', text:'하천 건너 탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m6_ember: {
      id: 'c2_m6_ember',
      title: 'CH2 M6 — Ember',
      chapter: 2,
      map: 'maps/campaign/ch2_m3_forest.json',
      bots: { blue: 4, red: 30 },
      nextMissionId: 'c2_m7_glasshouse',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'lmg1', secondary: 'pistol1', grenades: ['smoke','frag'], extras: ['flash','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.ATLAS,
          en:"They torch the trail behind. Keep moving or we get boxed.",
          ko:'뒤를 불태우고 있어. 계속 움직여. 갇힌다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'연기 속 전진' },
        { id:'reach_0', type:'reach', trigger:'a', label:'연기대' },
        { id:'obj_1', type:'objective', key:'b', text:'교차로 사수' },
        { id:'def_1', type:'defend', sec:40, text:'교차로 방어', objectiveKey:'b', checkpointId:'c2m6_hold' },
        { id:'obj_2', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m7_glasshouse: {
      id: 'c2_m7_glasshouse',
      title: 'CH2 M7 — Glasshouse',
      chapter: 2,
      map: 'maps/campaign/ch2_m4_city.json',
      bots: { blue: 3, red: 26 },
      nextMissionId: 'c2_m8_elevator',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar2', secondary: 'pistol1', grenades: ['flash','smoke'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"Corporate tower—clean floors, dirty deals. We go up.",
          ko:'기업 타워—겉은 깨끗, 속은 더럽다. 올라간다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'외곽 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'외곽' },
        { id:'obj_1', type:'objective', key:'b', text:'로비 확보' },
        { id:'reach_1', type:'reach', trigger:'b', label:'로비' },
        { id:'obj_2', type:'objective', key:'c', text:'서버실 접근' },
        { id:'inter_2', type:'interact', trigger:'c', label:'서버랙', hint:'E로 추출', toast:'데이터 추출', objectiveKey:'c', checkpointId:'c2m7_data' },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m8_elevator: {
      id: 'c2_m8_elevator',
      title: 'CH2 M8 — Elevator',
      chapter: 2,
      map: 'maps/campaign/ch2_m4_city.json',
      bots: { blue: 3, red: 32 },
      nextMissionId: 'c2_m9_frostline',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'shotgun1', secondary: 'pistol1', grenades: ['flash'], extras: ['smoke','frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.ATLAS,
          en:"We ride the lift blind. If doors open, we commit.",
          ko:'엘리베이터는 블라인드다. 문 열리면 밀어붙인다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'상층 접근' },
        { id:'reach_0', type:'reach', trigger:'a', label:'상층' },
        { id:'obj_1', type:'objective', key:'b', text:'복도 사수' },
        { id:'def_1', type:'defend', sec:30, text:'상층 복도 방어', objectiveKey:'b', checkpointId:'c2m8_hold' },
        { id:'obj_2', type:'objective', key:'exfil', text:'계단실로 탈출' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'계단실' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m9_frostline: {
      id: 'c2_m9_frostline',
      title: 'CH2 M9 — Frostline',
      chapter: 2,
      map: 'maps/campaign/ch2_m9_tundra.json',
      bots: { blue: 3, red: 24 },
      nextMissionId: 'c2_m10_whiteout',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'sr1', secondary: 'pistol1', grenades: ['smoke','flash'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.YARA,
          en:"Cold makes liars. Optics don't lie—if we stay steady.",
          ko:'추위는 거짓말을 만든다. 하지만 광학은 안 속아—침착하면.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'빙설지대 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'설원' },
        { id:'obj_1', type:'objective', key:'b', text:'관측 지점 확보' },
        { id:'reach_1', type:'reach', trigger:'b', label:'관측' },
        { id:'obj_2', type:'objective', key:'c', text:'신호기 회수' },
        { id:'inter_2', type:'interact', trigger:'c', label:'신호기', hint:'E로 회수', toast:'신호기 확보', objectiveKey:'c', checkpointId:'c2m9_beacon' },
        { id:'obj_3', type:'objective', key:'exfil', text:'철수' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'철수 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m10_whiteout: {
      id: 'c2_m10_whiteout',
      title: 'CH2 M10 — Whiteout',
      chapter: 2,
      map: 'maps/campaign/ch2_m9_tundra.json',
      bots: { blue: 3, red: 34 },
      nextMissionId: 'c2_m11_ironweave',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar3', secondary: 'pistol1', grenades: ['smoke','frag'], extras: ['flash','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"Storm's a cover. Use it. They will, too.",
          ko:'폭풍은 엄폐다. 이용해. 그쪽도 그럴 거야.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'설원 횡단' },
        { id:'reach_0', type:'reach', trigger:'a', label:'횡단선' },
        { id:'obj_1', type:'objective', key:'b', text:'임시 진지 방어' },
        { id:'def_1', type:'defend', sec:45, text:'진지 사수', objectiveKey:'b', checkpointId:'c2m10_hold' },
        { id:'obj_2', type:'objective', key:'exfil', text:'대피' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'대피 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m11_ironweave: {
      id: 'c2_m11_ironweave',
      title: 'CH2 M11 — Ironweave',
      chapter: 2,
      map: 'maps/campaign/ch2_m8_trainyard.json',
      bots: { blue: 4, red: 28 },
      nextMissionId: 'c2_m12_switchyard',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg1', secondary: 'pistol1', grenades: ['flash','smoke'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.RUNE,
          en:"Cargo moves by rail. We cut the rails, we cut the flow.",
          ko:'화물은 철도로 움직여. 철로를 끊으면 흐름도 끊겨.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'차량기지 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'기지' },
        { id:'obj_1', type:'objective', key:'b', text:'기관실 접근' },
        { id:'reach_1', type:'reach', trigger:'b', label:'기관실' },
        { id:'obj_2', type:'objective', key:'c', text:'차량 잠금 해제' },
        { id:'inter_2', type:'interact', trigger:'c', label:'패널', hint:'E로 해제', toast:'잠금 해제', objectiveKey:'c', checkpointId:'c2m11_unlock' },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m12_switchyard: {
      id: 'c2_m12_switchyard',
      title: 'CH2 M12 — Switchyard',
      chapter: 2,
      map: 'maps/campaign/ch2_m8_trainyard.json',
      bots: { blue: 4, red: 34 },
      nextMissionId: 'c2_m13_redhorizon',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'lmg2', secondary: 'pistol1', grenades: ['smoke','frag'], extras: ['flash','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"They’ll reroute once they smell us. We hold the switch.",
          ko:'우릴 눈치채면 우회한다. 스위치를 잡고 버텨.',
        },
        { id:'obj_0', type:'objective', key:'b', text:'분기점 확보' },
        { id:'reach_0', type:'reach', trigger:'b', label:'분기점' },
        { id:'obj_1', type:'objective', key:'hold', text:'분기점 방어' },
        { id:'def_1', type:'defend', sec:50, text:'분기점 사수', objectiveKey:'hold', checkpointId:'c2m12_hold' },
        { id:'obj_2', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m13_redhorizon: {
      id: 'c2_m13_redhorizon',
      title: 'CH2 M13 — Red Horizon',
      chapter: 2,
      map: 'maps/campaign/ch2_m5_mountains.json',
      bots: { blue: 3, red: 28 },
      nextMissionId: 'c2_m14_radiant',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar2', secondary: 'pistol1', grenades: ['smoke','flash'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"High ground isn't an advantage. It's a liability when they own the sky.",
          ko:'고지는 이점이 아니라 약점이 될 수 있어. 하늘을 그들이 잡으면.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'능선 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'능선' },
        { id:'obj_1', type:'objective', key:'b', text:'관측소 확보' },
        { id:'reach_1', type:'reach', trigger:'b', label:'관측소' },
        { id:'obj_2', type:'objective', key:'exfil', text:'후퇴' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'후퇴 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m14_radiant: {
      id: 'c2_m14_radiant',
      title: 'CH2 M14 — Radiant',
      chapter: 2,
      map: 'maps/campaign/ch2_m5_mountains.json',
      bots: { blue: 3, red: 36 },
      nextMissionId: 'c2_m15_refinery',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'dmr2', secondary: 'pistol1', grenades: ['flash','frag'], extras: ['smoke','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.KESTREL,
          en:"Thermal bloom ahead. Something’s running hot.",
          ko:'열 흔적이 커. 뭔가 과열 중이다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'접근' },
        { id:'reach_0', type:'reach', trigger:'a', label:'접근선' },
        { id:'obj_1', type:'objective', key:'c', text:'장비 확보' },
        { id:'inter_1', type:'interact', trigger:'c', label:'케이스', hint:'E로 확보', toast:'장비 확보', objectiveKey:'c', checkpointId:'c2m14_case' },
        { id:'obj_2', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m15_refinery: {
      id: 'c2_m15_refinery',
      title: 'CH2 M15 — Refinery',
      chapter: 2,
      map: 'maps/campaign/ch2_m6_refinery.json',
      bots: { blue: 4, red: 30 },
      nextMissionId: 'c2_m16_breakwater',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['smoke','frag'], extras: ['flash','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.ATLAS,
          en:"Fuel equals time. We steal their time.",
          ko:'연료는 시간이다. 그 시간을 빼앗는다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'정유시설 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'시설 외곽' },
        { id:'obj_1', type:'objective', key:'b', text:'밸브 구역 확보' },
        { id:'reach_1', type:'reach', trigger:'b', label:'밸브' },
        { id:'obj_2', type:'objective', key:'c', text:'밸브 차단' },
        { id:'inter_2', type:'interact', trigger:'c', label:'밸브', hint:'E로 차단', toast:'밸브 차단', objectiveKey:'c', checkpointId:'c2m15_valve' },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m16_breakwater: {
      id: 'c2_m16_breakwater',
      title: 'CH2 M16 — Breakwater',
      chapter: 2,
      map: 'maps/campaign/ch2_m7_ruins.json',
      bots: { blue: 4, red: 34 },
      nextMissionId: 'c2_m17_offshore',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg3', secondary: 'pistol1', grenades: ['flash','smoke'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.RUNE,
          en:"Ruins mean angles. Don't get greedy.",
          ko:'폐허는 각이 많아. 욕심내지 마.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'폐허 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'폐허' },
        { id:'obj_1', type:'objective', key:'b', text:'방파제 확보' },
        { id:'def_1', type:'defend', sec:40, text:'방파제 사수', objectiveKey:'b', checkpointId:'c2m16_hold' },
        { id:'obj_2', type:'objective', key:'exfil', text:'후퇴' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'후퇴 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m17_offshore: {
      id: 'c2_m17_offshore',
      title: 'CH2 M17 — Offshore',
      chapter: 2,
      map: 'maps/campaign/ch2_m10_offshore.json',
      bots: { blue: 3, red: 30 },
      nextMissionId: 'c2_m18_blackbox',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'sr2', secondary: 'pistol1', grenades: ['smoke','flash'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"Satellite pings trace to the rigs. We prove it—then we burn it.",
          ko:'위성 핑이 해상 시설로 이어진다. 증명하고... 태운다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'플랫폼 접근' },
        { id:'reach_0', type:'reach', trigger:'a', label:'플랫폼' },
        { id:'obj_1', type:'objective', key:'c', text:'중계 장치 확보' },
        { id:'inter_1', type:'interact', trigger:'c', label:'중계기', hint:'E로 확보', toast:'장치 확보', objectiveKey:'c', checkpointId:'c2m17_relay' },
        { id:'obj_2', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m18_blackbox: {
      id: 'c2_m18_blackbox',
      title: 'CH2 M18 — Blackbox',
      chapter: 2,
      map: 'maps/campaign/ch2_m6_refinery.json',
      bots: { blue: 3, red: 36 },
      nextMissionId: 'c2_m19_scar',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar3', secondary: 'pistol1', grenades: ['flash','smoke'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.KESTREL,
          en:"We found the payment chain. Next is the buyer.",
          ko:'결제 체인을 찾았다. 다음은 구매자다.',
        },
        { id:'obj_0', type:'objective', key:'b', text:'제어실 확보' },
        { id:'reach_0', type:'reach', trigger:'b', label:'제어실' },
        { id:'obj_1', type:'objective', key:'c', text:'블랙박스 추출' },
        { id:'inter_1', type:'interact', trigger:'c', label:'블랙박스', hint:'E로 추출', toast:'블랙박스 확보', objectiveKey:'c', checkpointId:'c2m18_blackbox' },
        { id:'obj_2', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m19_scar: {
      id: 'c2_m19_scar',
      title: 'CH2 M19 — Scar',
      chapter: 2,
      map: 'maps/campaign/ch2_m5_mountains.json',
      bots: { blue: 2, red: 40 },
      nextMissionId: 'c2_m20_nemesis',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'dmr2', secondary: 'pistol1', grenades: ['smoke','flash'], extras: ['frag','impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"We’re close. So close it hurts. Don’t blink.",
          ko:'거의 다 왔다. 아플 정도로. 한눈팔지 마.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'능선 돌파' },
        { id:'reach_0', type:'reach', trigger:'a', label:'돌파선' },
        { id:'obj_1', type:'objective', key:'b', text:'절벽길 확보' },
        { id:'def_1', type:'defend', sec:55, text:'절벽길 사수', objectiveKey:'b', checkpointId:'c2m19_hold' },
        { id:'obj_2', type:'objective', key:'exfil', text:'전진' },
        { id:'reach_2', type:'reach', trigger:'exfil', label:'전진 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c2_m20_nemesis: {
      id: 'c2_m20_nemesis',
      title: 'CH2 M20 — Nemesis',
      chapter: 2,
      map: 'maps/campaign/ch2_m10_offshore.json',
      bots: { blue: 3, red: 44 },
      nextMissionId: null,
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar2', secondary: 'pistol1', grenades: ['smoke','flash','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.NOVA,
          en:"This is the hub. Pull the plug, and the storm ends.",
          ko:'여기가 허브다. 플러그를 뽑으면 폭풍은 끝난다.',
        },
        { id:'obj_0', type:'objective', key:'a', text:'플랫폼 진입' },
        { id:'reach_0', type:'reach', trigger:'a', label:'플랫폼' },
        { id:'dlg_1', type:'say', speaker:CAST.ATLAS,
          en:"No reinforcements. It's just us and the truth.",
          ko:'증원 없다. 우리와 진실뿐이다.',
        },
        { id:'obj_1', type:'objective', key:'b', text:'코어룸 확보' },
        { id:'reach_1', type:'reach', trigger:'b', label:'코어룸' },
        { id:'obj_2', type:'objective', key:'c', text:'코어 차단' },
        { id:'inter_2', type:'interact', trigger:'c', label:'코어', hint:'E로 차단', toast:'코어 차단', objectiveKey:'c', checkpointId:'c2m20_core' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"Done. Now we disappear.",
          ko:'끝. 이제 사라진다.',
        },
        { id:'obj_3', type:'objective', key:'exfil', text:'탈출' },
        { id:'reach_3', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },
  },
};
