// src/campaign/CampaignData.js
// Campaign data (MW-like pacing, original cast & setting).

export const CAMPAIGN_KEY = 'strikegy_campaign_v1';

// CAST (original; avoid direct CoD names)
// - CAPTAIN HART: field commander (mentor)
// - SHADE: stealth operator / recon
// - RAVEN: player callsign
export const CAST = {
  HART: 'CAPTAIN HART',
  SHADE: 'SHADE',
  RAVEN: 'RAVEN',
};

// Framework supports step types:
// - cutscene: camera rails + cinematic bars/fade + input lock
// - say: TTS(EN) + KO subtitles
// - objective: sets current objective + adds to checklist
// - reach: reach trigger sphere in campaign map
// - kill: reach kill count
// - complete: mission success
// Runtime fail handling:
// - mission.failOnDeath: true => death triggers fail overlay

export const CampaignDB = {
  missions: {
    c1_m1_insertion: {
      id: 'c1_m1_insertion',
      title: 'CH1 M1 — Insertion',
      chapter: 1,
      map: 'maps/campaign/ch1_m1_insertion.json',
      bots: { blue: 0, red: 8 },
      nextMissionId: 'c1_m2_blacksite',
      // Campaign rules (override PvP systems)
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      // Fixed loadout (no purchases). Slots stay the same.
      loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['frag','flash','smoke'], extras: ['impact'] },
      failOnDeath: true,
      // Optional: mission time limit (seconds). 0 = none.
      timeLimitSec: 0,

      // Script sequence (10~20min target; MVP is short but structured for expansion)
      script: [
        { id:'cs_intro', type:'cutscene', duration:7.2, lockPlayer:true,
          cinematic:{ bars:true, fadeIn:0.5, fadeOut:0.4 },
          camera:[
            { t:0.0, pos:[-155,3.4,-20], look:[-124,2.1,-2] },
            { t:2.4, pos:[-146,3.8,-10], look:[-120,2.2, 8] },
            { t:4.8, pos:[-136,4.1,  6], look:[-106,2.3,18] },
            { t:7.2, pos:[-126,3.6, 18], look:[ -94,2.2,28] },
          ],
        },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Raven—sun’s up. We’re late, so we stay quiet.",
          ko:'레이븐—해가 떴다. 늦었으니 조용히 간다.',
        },
        { id:'obj_rally', type:'objective', key:'rally', text:'집결 지점으로 이동' },
        { id:'reach_rally', type:'reach', trigger:'rally', label:'집결 지점' },
        { id:'dlg_2', type:'say', speaker:CAST.SHADE,
          en:"Camp comms are on a short loop. Tap the relay—then we move.",
          ko:'캠프 통신이 짧게 반복돼. 중계기 건드리고 바로 빠져.',
        },
        { id:'obj_relay', type:'objective', key:'relay', text:'임시 중계기 해킹' },
        { id:'hack', type:'interact', trigger:'rally', label:'중계기', hint:'E로 해킹',
          toast:'신호 루프 차단', objectiveKey:'relay', checkpointId:'relay' },
        { id:'dlg_3', type:'say', speaker:CAST.HART,
          en:"They heard that. Take the outer ring, clean what follows.",
          ko:'들켰다. 외곽으로 빠지며 뒤따르는 놈들 정리해.',
        },
        { id:'obj_elim', type:'objective', key:'elim6', text:'추격 적 제거 (6)' },
        { id:'kill_6', type:'kill', count:6, team:'red' },
        { id:'dlg_4', type:'say', speaker:CAST.SHADE,
          en:"Dust is shifting—watch the ridge. Exfil marker is live.",
          ko:'먼지 흐름이 바뀐다—능선 조심. 탈출 마커 열림.',
        },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'탈출 지점 확보' },
        { id:'wait_pickup', type:'wait', sec:3.5, text:'픽업 신호 송신 중', checkpointId:'pickup_ping' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
          { id:'end', type:'complete' }
        ],
      },
  
      c1_m1_insertion_alt: {
        id: 'c1_m1_insertion_alt',
        title: 'CH1 M1 — Insertion (Alt)',
        chapter: 1,
        map: 'maps/campaign/ch1_m1_insertion.json',
        bots: { blue: 0, red: 8 },
        nextMissionId: 'c1_m2_blacksite',
        rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
        loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['frag','flash','smoke'], extras: ['impact'] },
        failOnDeath: true,
        timeLimitSec: 0,
        script: [
          {
            id: 'dlg_1',
          type: 'say',
          speaker: CAST.HART,
          en: "Raven. Eyes up. We’ve got movement in the dust.",
          ko: '레이븐. 전방 주시. 먼지 속에 움직임이 있다.',
        },
        {
          id: 'obj_rally',
          type: 'objective',
          key: 'rally',
          text: '집결 지점으로 이동',
        },
        {
          id: 'reach_rally',
          type: 'reach',
          trigger: 'rally',
          label: '집결 지점',
        },
        {
          id: 'dlg_2',
          type: 'say',
          speaker: CAST.SHADE,
          en: "Two patrols. East side. Keep your silhouette low.",
          ko: '순찰 둘. 동쪽. 실루엣 낮춰.',
        },
        {
          id: 'obj_elim',
          type: 'objective',
          key: 'elim5',
          text: '적 5명 제거',
        },
        {
          id: 'kill_5',
          type: 'kill',
          count: 5,
          team: 'red',
        },
        {
          id: 'dlg_3',
          type: 'say',
          speaker: CAST.HART,
          en: "Clean. Don’t linger—exfil is north. Move.",
          ko: '깔끔하다. 지체하지 마—탈출 지점은 북쪽. 이동.',
        },
        {
          id: 'obj_exfil',
          type: 'objective',
          key: 'exfil',
          text: '탈출 지점 확보',
        },
        {
          id: 'reach_exfil',
          type: 'reach',
          trigger: 'exfil',
          label: '탈출 지점',
        },
        {
          id: 'end',
          type: 'complete',
        },
      ],
    },

    // --- CH1: "DUSTLINE" (10 missions, MW-like pacing; original setting/cast) ---
    c1_m2_blacksite: {
      id: 'c1_m2_blacksite',
      title: 'CH1 M2 — Blacksite',
      chapter: 1,
      map: 'maps/campaign/ch1_m2_blacksite.json',
      bots: { blue: 2, red: 10 },
      nextMissionId: 'c1_m3_convoy',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg1', secondary: 'pistol1', grenades: ['flash','frag','smoke'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'cs_entry', type:'cutscene', duration:6.6, lockPlayer:true,
          cinematic:{ bars:true, fadeIn:0.4, fadeOut:0.25 },
          camera:[
            { t:0.0, pos:[-85,3.6,-70], look:[-60,2.4,-42] },
            { t:2.0, pos:[-70,3.3,-55], look:[-40,2.2,-25] },
            { t:4.0, pos:[-52,3.0,-40], look:[-20,2.0, -6] },
            { t:6.6, pos:[-42,2.8,-28], look:[-10,2.0, 10] },
          ],
        },
        { id:'dlg_1', type:'say', speaker:CAST.HART,
          en:"Blacksite door. No shop, no kit—just what you carry.",
          ko:'블랙사이트 문이다. 상점/키트 없음—들고 있는 걸로 간다.',
        },
        { id:'obj_breach', type:'objective', key:'breach', text:'출입문 돌파' },
        { id:'breach', type:'interact', trigger:'breach', label:'출입문', hint:'E로 돌파',
          toast:'문 개방', objectiveKey:'breach', checkpointId:'breach' },
        { id:'dlg_2', type:'say', speaker:CAST.SHADE,
          en:"Camera grid is old. Move fast between the lights.",
          ko:'감시망이 구식이야. 조명 사이로 빠르게.',
        },
        { id:'obj_intel', type:'objective', key:'intel', text:'자료실에서 데이터 확보' },
        { id:'reach_intel', type:'reach', trigger:'intel', label:'자료실' },
        { id:'grab', type:'interact', trigger:'intel', label:'단말기', hint:'E로 다운로드 시작',
          toast:'다운로드 시작', checkpointId:'dl_start' },
        { id:'wait_dl', type:'wait', sec:8.0, text:'데이터 다운로드', objectiveKey:'intel', checkpointId:'dl_done' },
        { id:'dlg_3', type:'say', speaker:CAST.HART,
          en:"Alarm—hold that corridor! Thirty seconds!",
          ko:'경보! 복도에서 버텨! 30초!',
        },
        { id:'obj_hold', type:'objective', key:'hold', text:'복도 방어' },
        { id:'defend', type:'defend', sec:30, text:'위치 사수', objectiveKey:'hold', checkpointId:'hold_30' },
        { id:'dlg_4', type:'say', speaker:CAST.SHADE,
          en:"Route’s clear. Exfil on the far side.",
          ko:'루트 확보. 반대편으로 탈출.',
        },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'탈출 지점으로 이동' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m3_convoy: {
      id: 'c1_m3_convoy',
      title: 'CH1 M3 — Convoy',
      chapter: 1,
      map: 'maps/campaign/ch1_m3_convoy.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m4_bridge',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar2', secondary: 'pistol1', grenades: ['frag','smoke','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Convoy’s rolling. We don’t stop it—we cut its memory.",
          ko:'호송대가 이동 중이다. 멈추는 게 아니라 ‘기억’을 자른다.',
        },
        { id:'obj_amb', type:'objective', key:'ambush', text:'매복 지점 확보' },
        { id:'reach_amb', type:'reach', trigger:'ambush', label:'매복 지점' },
        { id:'wait_pass', type:'wait', sec:5.0, text:'호송대 접근 대기', checkpointId:'convoy_in' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Target case—rear truck. Take it and burn the route.",
          ko:'목표 케이스—후미 트럭. 회수하고 루트를 태워.',
        },
        { id:'obj_disable', type:'objective', key:'case', text:'케이스 회수' },
        { id:'pickup', type:'interact', trigger:'pickup', label:'케이스', hint:'E로 회수',
          toast:'케이스 확보', objectiveKey:'case', checkpointId:'case' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"They’re turning back—deny the road. Ten hostiles.",
          ko:'되돌아온다—도로 차단. 적 10.',
        },
        { id:'obj_elim', type:'objective', key:'elim10', text:'적 10명 제거' },
        { id:'kill_10', type:'kill', count:10, team:'red' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m4_bridge: {
      id: 'c1_m4_bridge',
      title: 'CH1 M4 — Bridge',
      chapter: 1,
      map: 'maps/campaign/ch1_m4_bridge.json',
      bots: { blue: 3, red: 14 },
      nextMissionId: 'c1_m5_city',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'lmg1', secondary: 'pistol1', grenades: ['smoke','frag','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Bridge is the throat. We cross, or we choke.",
          ko:'다리는 목줄이다. 건너야 숨을 쉰다.',
        },
        { id:'obj_bridge', type:'objective', key:'bridge', text:'교량 진입' },
        { id:'reach_bridge', type:'reach', trigger:'bridge', label:'교량' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Smoke then sprint. Don’t bunch up.",
          ko:'연막 치고 전력 질주. 뭉치지 마.',
        },
        { id:'obj_push', type:'objective', key:'push', text:'교량 돌파' },
        { id:'defend_mid', type:'defend', sec:22, text:'중간 지점 돌파', objectiveKey:'push', checkpointId:'bridge_mid' },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'교량 끝 확보' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m5_city: {
      id: 'c1_m5_city',
      title: 'CH1 M5 — Cityline',
      chapter: 1,
      map: 'maps/campaign/ch1_m5_city.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m6_trench',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar1', secondary: 'pistol1', grenades: ['flash','smoke','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"City’s awake. Civilians gone—only echoes left.",
          ko:'도시가 깨어났다. 민간인은 사라지고, 메아리만 남았다.',
        },
        { id:'obj_street', type:'objective', key:'street', text:'골목길로 진입' },
        { id:'reach_street', type:'reach', trigger:'street', label:'골목' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"We need eyes. Rooftop gives angles—take it.",
          ko:'시야가 필요해. 옥상에서 각을 잡아—올라가.',
        },
        { id:'obj_roof', type:'objective', key:'roof', text:'고지 확보' },
        { id:'reach_roof', type:'reach', trigger:'rooftop', label:'고지' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"Mark the route. Then we disappear.",
          ko:'루트 표시하고 사라진다.',
        },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'도시 외곽으로 탈출' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m6_trench: {
      id: 'c1_m6_trench',
      title: 'CH1 M6 — Trenchwork',
      chapter: 1,
      map: 'maps/campaign/ch1_m6_trench.json',
      bots: { blue: 3, red: 16 },
      nextMissionId: 'c1_m7_ridge',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'sg1', secondary: 'pistol1', grenades: ['smoke','frag','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"No-man’s-land. Keep your head down—sound carries.",
          ko:'노맨즈랜드. 머리 숙여—소리가 멀리 간다.',
        },
        { id:'obj_l1', type:'objective', key:'line1', text:'1차 참호선 확보' },
        { id:'reach_l1', type:'reach', trigger:'line1', label:'1차 참호선' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"They’re dug in. Push by segments—don’t overextend.",
          ko:'파고들어있다. 구간별로 밀어—깊게 나가지 마.',
        },
        { id:'obj_l2', type:'objective', key:'line2', text:'2차 참호선 확보' },
        { id:'reach_l2', type:'reach', trigger:'line2', label:'2차 참호선' },
        { id:'obj_l3', type:'objective', key:'line3', text:'3차 참호선 확보' },
        { id:'reach_l3', type:'reach', trigger:'line3', label:'3차 참호선' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m7_ridge: {
      id: 'c1_m7_ridge',
      title: 'CH1 M7 — Ridgeline',
      chapter: 1,
      map: 'maps/campaign/ch1_m7_ridge.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m8_counter',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'sr1', secondary: 'pistol1', grenades: ['smoke','flash','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Relay tower. If it stays up, they see everything.",
          ko:'중계탑이다. 살아있으면 놈들이 전부 본다.',
        },
        { id:'obj_yard', type:'objective', key:'yard', text:'야적장 진입' },
        { id:'reach_yard', type:'reach', trigger:'yard', label:'야적장' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Plant a charge—make it look like an accident.",
          ko:'폭약 설치해. 사고처럼 보이게.',
        },
        { id:'obj_tower', type:'objective', key:'tower', text:'중계장치 파괴' },
        { id:'inter_tower', type:'interact', trigger:'tower', label:'중계장치', hint:'E로 폭약 설치',
          toast:'폭약 설치', objectiveKey:'tower', checkpointId:'tower_charge' },
        { id:'wait_boom', type:'wait', sec:3.0, text:'기폭', checkpointId:'boom' },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'이탈' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m8_counter: {
      id: 'c1_m8_counter',
      title: 'CH1 M8 — Counterstrike',
      chapter: 1,
      map: 'maps/campaign/ch1_m8_counter.json',
      bots: { blue: 3, red: 18 },
      nextMissionId: 'c1_m9_lab',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'lmg2', secondary: 'pistol1', grenades: ['smoke','frag','flash'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Subway’s a straight line—until it isn’t. Stay sharp.",
          ko:'지하철은 직선이다… 그렇지 않을 때까지. 집중해.',
        },
        { id:'obj_plat', type:'objective', key:'platform', text:'플랫폼 접근' },
        { id:'reach_plat', type:'reach', trigger:'platform', label:'플랫폼' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Switch room. We reroute the gates.",
          ko:'전환실. 게이트 우회한다.',
        },
        { id:'obj_switch', type:'objective', key:'switch', text:'전환기 조작' },
        { id:'inter_switch', type:'interact', trigger:'switch', label:'전환기', hint:'E로 조작',
          toast:'선로 전환', objectiveKey:'switch', checkpointId:'switch' },
        { id:'wait_gate', type:'wait', sec:4.0, text:'게이트 개방', checkpointId:'gate_open' },
        { id:'obj_escape', type:'objective', key:'escape', text:'터널을 빠져나가기' },
        { id:'reach_escape', type:'reach', trigger:'escape', label:'탈출' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m9_lab: {
      id: 'c1_m9_lab',
      title: 'CH1 M9 — The Lab',
      chapter: 1,
      map: 'maps/campaign/ch1_m9_lab.json',
      bots: { blue: 2, red: 12 },
      nextMissionId: 'c1_m10_exodus',
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'smg4', secondary: 'pistol1', grenades: ['flash','smoke','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Embassy’s a symbol. We extract the person, not the pride.",
          ko:'대사관은 상징이다. 우리는 자존심이 아니라 ‘사람’을 빼낸다.',
        },
        { id:'obj_gate', type:'objective', key:'gate', text:'정문 접근' },
        { id:'reach_gate', type:'reach', trigger:'gate', label:'정문' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"VIP is inside. Quiet hands.",
          ko:'VIP는 안쪽이다. 손을 조용히.',
        },
        { id:'obj_vip', type:'objective', key:'vip', text:'VIP 확보' },
        { id:'inter_vip', type:'interact', trigger:'vip', label:'VIP', hint:'E로 확보',
          toast:'VIP 확보', objectiveKey:'vip', checkpointId:'vip' },
        { id:'obj_exfil', type:'objective', key:'exfil', text:'호위하며 탈출' },
        { id:'reach_exfil', type:'reach', trigger:'exfil', label:'탈출 지점' },
        { id:'end', type:'complete' }
      ],
    },

    c1_m10_exodus: {
      id: 'c1_m10_exodus',
      title: 'CH1 M10 — Exodus',
      chapter: 1,
      map: 'maps/campaign/ch1_m10_exodus.json',
      bots: { blue: 3, red: 20 },
      nextMissionId: null,
      rules: { noShop: true, noClass: true, noBandage: true, autoRegen: true },
      loadout: { primary: 'ar3', secondary: 'pistol1', grenades: ['smoke','flash','frag'], extras: ['impact'] },
      failOnDeath: true,
      timeLimitSec: 0,
      script: [
        { id:'dlg_0', type:'say', speaker:CAST.HART,
          en:"Canyon LZ. If we miss the window, we’re buried here.",
          ko:'협곡 착륙지점. 타이밍 놓치면 여기서 묻힌다.',
        },
        { id:'obj_push', type:'objective', key:'push', text:'전진' },
        { id:'reach_push', type:'reach', trigger:'push', label:'전진 지점' },
        { id:'dlg_1', type:'say', speaker:CAST.SHADE,
          en:"Hold the bowl—eyes on the ridges.",
          ko:'분지에서 버텨. 능선 주시.',
        },
        { id:'obj_hold', type:'objective', key:'hold', text:'착륙지점 방어' },
        { id:'def_hold', type:'defend', sec:35, text:'착륙지점 사수', objectiveKey:'hold', checkpointId:'lz_hold' },
        { id:'dlg_2', type:'say', speaker:CAST.HART,
          en:"Bird’s in. Move, move—LZ now!",
          ko:'헬기 도착. 이동, 이동—지금 LZ!',
        },
        { id:'obj_lz', type:'objective', key:'lz', text:'착륙지점 진입' },
        { id:'reach_lz', type:'reach', trigger:'lz', label:'LZ' },
        { id:'end', type:'complete' }
      ],
    },
  },
};
